### ISSUE TITLE
Make it possible to install the package with `go install`

### ISSUE THREAD

**Issue by ralienpp** [zjj/golibkit#1]
If I run  `go install github.com/zjj/golibkit@latest` in order to be able to use the package in my program, the following error is shown:

`go: github.com/zjj/golibkit@latest: module github.com/zjj/golibkit@latest found (v0.0.0-20220430050742-b7a93c743cee), but does not contain package github.com/zjj/golibkit`

How could one use the library in other software?

**Comment by zjj** [comment]
***@***.*** pp$ go get ***@***.***
go get: added github.com/zjj/golibkit v0.0.0-20220430050742-b7a93c743cee

seems no error, "go install", I not sure, I use "go get"

**Comment by zjj** [comment]
try below cmd if you know what you want.
`GO111MODULE="off" go get github.com/zjj/golibkit`
